import os

def preprocess_corpus(input_path: str, output_path: str):
    if not os.path.exists(input_path):
        print(f"File {input_path} not found.")
        return
        
    orig_size = os.path.getsize(input_path)
    
    with open(input_path, 'r', encoding='utf-8') as f:
        text = f.read()
        
    # Remove null bytes
    text = text.replace('\x00', '')
    
    # Normalize line endings
    text = text.replace('\r\n', '\n').replace('\r', '\n')
    
    # Remove lines containing generated keywords
    lines = text.split('\n')
    clean_lines = []
    for line in lines:
        lower_line = line.lower()
        if "do not edit" in lower_line or "auto-generated" in lower_line or "autogenerated" in lower_line:
            continue
        clean_lines.append(line)
        
    text = '\n'.join(clean_lines)
    
    # Collapse 3+ consecutive blank lines to 2
    while '\n\n\n\n' in text:
        text = text.replace('\n\n\n\n', '\n\n\n')
        
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(text)
        
    clean_size = os.path.getsize(output_path)
    reduction = 100.0 * (1.0 - clean_size / max(orig_size, 1))
    
    print(f"Original size: {orig_size / (1024*1024):.2f} MB")
    print(f"Cleaned size:  {clean_size / (1024*1024):.2f} MB")
    print(f"Reduction:     {reduction:.2f}%")
